version: '3.8'

services:
#  rabbitmq:
#    image: rabbitmq:management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    volumes:
#      - rabbitmq_data:/var/lib/rabbitmq
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"

  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: dinestream_kitchen
      POSTGRES_USER: kitchen
      POSTGRES_PASSWORD: kitchen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  postgres_data: